import React from 'react';
import { renderHook } from '@testing-library/react-native';
import useSnackbar from '../useSnackbar';
import { SnackbarContext } from '../SnackbarProvider';

describe('useSnackbar hook', () => {
  it('throws an error if SnackbarCTX is missing', () => {
    // We want to suppress the console.error output generated by React boundary for cleaner logs
    const originalError = console.error;
    console.error = jest.fn();

    // Mock useContext to return undefined to simulate missing context
    jest.spyOn(React, 'useContext').mockReturnValue(undefined as any);

    expect(() => renderHook(() => useSnackbar())).toThrow(
      'useSnackbar must be used within a SnackbarProvider.'
    );

    jest.restoreAllMocks();
    console.error = originalError;
  });

  it('returns context value successfully', () => {
    const showMock = jest.fn();
    const hideMock = jest.fn();

    const wrapper = ({ children }: { children: React.ReactNode }) => (
      <SnackbarContext.Provider value={{ show: showMock, hide: hideMock }}>
        {children}
      </SnackbarContext.Provider>
    );

    const { result } = renderHook(() => useSnackbar(), { wrapper });

    expect(result.current).toHaveProperty('show');
    expect(result.current).toHaveProperty('hide');
    expect(result.current.show).toBe(showMock);
    expect(result.current.hide).toBe(hideMock);
  });
});
